name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: SWETHACS17
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: #00FF00
          color_dots: #161b22,#0e4429,#006d32,#26a641,#39d353  # GitHub dark theme

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
